website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db  # means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user
from datetime import datetime


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        # If user is already logged in, redirect to a different page
        # Change 'dashboard' to your desired route
        return redirect(url_for('views.select_role'))

    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        print("USER DETAILS")
        print(user)
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                if user.user_role == 'user':
                    return redirect(url_for('views.select_role'))
                else:
                    return redirect(url_for('views.admin_page'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.home'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if current_user.is_authenticated:
        # If user is already logged in, redirect to a different page
        return redirect(url_for('views.select_role'))

    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        user_role = 'user'
        date = datetime.now()

        user = User.query.filter_by(first_name=first_name).first()
        if user:
            flash('Username already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('Username must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='sha256'), user_role=user_role, date=date)
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.select_role'))

    return render_template("signup.html", user=current_user)

website/templates/about.html
{% extends "base.html" %} {% block title %}Spatial{% endblock %} {% block content %}  

<div class="container-fluid" autoFocus='false' style="margin-top: 200px;">
    <h1 class="jumbotron-text display-1 text-center mb-0" style="font-size: 150px;">
        <p class="lead jumbotron-text text-center mb-0">   <b>ABOUT PAGE </b></p>
    </h1></br>


{% endblock %}

website/templates/admin_page.html
{% extends "base.html" %} {% block title %}Spatial{% endblock %} {% block content %}

<div class="container-fluid" autoFocus='false' style="margin-top: 200px;">
    <h1 class="jumbotron-text display-1 text-center mb-0" style="font-size: 150px;">
        <p class="lead jumbotron-text text-center mb-0"> <b>ADMIN PAGE </b></p>
    </h1></br>


    {% endblock %}

website/templates/base.html
<!--
=========================================================
* Argon Dashboard - v1.2.0
=========================================================
* Product Page: https://www.creative-tim.com/product/argon-dashboard


* Copyright  Creative Tim (http://www.creative-tim.com)
* Coded by www.creative-tim.com



=========================================================
* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="canonical" href="https://appseed.us/admin-dashboards/flask-boilerplate-dashboard-argon">

  <title>
    Spatial - {% block title %} {% endblock %}
  </title>
  <style>
  </style>

  <!-- Favicon - loaded as static -->
  <link rel="icon" href="/static/assets/LogReg.png" type="image/png">
  <!-- Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
  <!-- Icons -->
  <link rel="stylesheet" href="/static/assets/vendor/nucleo/css/nucleo.css" type="text/css">
  <link rel="stylesheet" href="/static/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css" type="text/css">
  <!-- Page plugins -->
  <!-- Argon CSS -->
  <link rel="stylesheet" href="/static/assets/css/argon.css?v=1.2.0" type="text/css">

  <!-- Specific CSS goes HERE -->
  {% block stylesheets %}{% endblock stylesheets %}

</head>

<body class="">

  {% include "sidenav.html" %}

  <div class="main-content" id="panel">

    {% include "navigation.html" %}

    <div class="container1"> {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %} {% for category, message in messages %} {% if category ==
      'error' %}
      <div class="alert alert-danger alter-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% else %}
      <div class="alert alert-success alter-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      {% endif %} {% endfor %} {% endif %} {% endwith %}{% block content %}{% endblock content %}
    </div>


    {% include "footer-fullscreen.html" %}



  </div>

  {% include "scripts.html" %}

  <!-- Specific JS goes HERE -->
  {% block javascripts %}{% endblock javascripts %}

  <script src="/static/assets/js/argon.js?v=1.2.0"></script>

</body>

</html>

website/templates/footer-fullscreen.html
<style>
  /* footer {
    position: relative;
    bottom: 0;
    left: 0;
    right: 0;
  } */

  .container {
    position: fixed;
    bottom: 3%;
    left: 0;
    right: 0;
  }
</style>
<footer class="py-5">
  <div class="container">
    <div class="row align-items-center justify-content-xl-between">
      <div class="col-xl-6">
        <div class="copyright text-center text-xl-left text-muted">
          <a target="_blank" href="https://spatial-h2020.eu/" class="font-weight-bold ml-1" target="_blank">Spatial</a>
        </div>
      </div>
      <div class="col-xl-6">
        <div class="text-center text-xl-right text-muted">
          <a>UTSpatial&copy;2023 Developed by <a target="_blank" href="https://dps.cs.ut.ee/index.html">UT</a>. Version
            0.3</a>
        </div>
      </div>
    </div>
  </div>
</footer>

website/templates/footer.html
<!-- Footer -->
<style>
  footer {
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
  }
</style>
<footer class="footer">
  <div class="row align-items-center justify-content-xl-between">
    <div class="col-xl-6">
      <div class="text-center text-xl-left text-muted">
        <a target="_blank" href="https://spatial-h2020.eu/" class="font-weight-bold ml-1" target="_blank">Spatial</a>
      </div>
    </div>
    <div class="col-xl-6">
      <div class="text-center text-xl-right text-muted">
        <a>UTSpatial&copy;2023 Developed by <a target="_blank" href="https://dps.cs.ut.ee/index.html">UT</a>. Version
          0.3</a>
      </div>
    </div>
  </div>
</footer>

website/templates/home.html
{% extends "base.html" %} {% block title %}Spatial{% endblock %} {% block content %}  

    <div class="container-fluid" autoFocus='false' style="margin-top: 200px;">
    <h1 class="jumbotron-text display-1 text-center mb-0 navbar-dark bg-primary" style="font-size: 150px; ">
        <img src="{{ url_for('static', filename='assets/Spatial_Logo.png') }}" alt="Spatial Logo">
    </h1></br>
  <p class="lead jumbotron-text text-center mb-0">   <b>Achieving trustworthy, transparent and explainable AI
        for cybersecurity solutions </b></p>
        
  </div> {% endblock %}


website/templates/login.html
{% extends "base.html" %}

{% block title %}
Login
{% endblock %}

{% block content %}



<section class="vh-80" style="margin-top: 70px; overflow-x: hidden;">
  <div class="row justify-content-center">
    <div class="col-lg-12 col-xl-11">
      <div class="card text-white p-md-5 navbar-dark"
        style="border-radius: 25px;  box-shadow: 0px 0px 5px 0px  rgba(0, 0, 0, 0.75);">
        <div class="card-body p-md-5">
          <div class="row justify-content-center">
            <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
              <form method="POST" style="color: black; ">
                <h3 align="center">Login</h3><br>
                <div class="form-group">
                  <label for="email">Email Address</label>
                  <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" required />
                </div>
                <div class="form-group">
                  <label for="password">Password</label>
                  <input type="password" class="form-control" id="password" name="password" placeholder="Enter password"
                    required />
                </div>
                <br />
                <div class="text-center">
                  <button type="submit" class="btn btn-primary">Login</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

website/templates/navigation.html
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Search form -->
      <!-- <form class="navbar-search navbar-search-light form-inline mr-sm-3" id="navbar-search-main">
        <div class="form-group mb-0">
          <div class="input-group input-group-alternative input-group-merge">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-search"></i></span>
            </div>
            <input class="form-control" placeholder="Search" type="text">
          </div>
        </div>
        <button type="button" class="close" data-action="search-close" data-target="#navbar-search-main"
          aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </form> -->
      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center  ml-md-auto ">
        <li class="nav-item d-xl-none">
          <!-- Sidenav toggler -->
          <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </div>
        </li>
        <li class="nav-item d-sm-none">
          <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
            <i class="ni ni-zoom-split-in"></i>
          </a>
        </li>

        <!-- <li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ni ni-ungroup"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-dark bg-default  dropdown-menu-right ">
            <div class="row shortcuts px-4">
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-red">
                  <i class="ni ni-calendar-grid-58"></i>
                </span>
                <small>Calendar</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-orange">
                  <i class="ni ni-email-83"></i>
                </span>
                <small>Email</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-info">
                  <i class="ni ni-credit-card"></i>
                </span>
                <small>Payments</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-green">
                  <i class="ni ni-books"></i>
                </span>
                <small>Reports</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-purple">
                  <i class="ni ni-pin-3"></i>
                </span>
                <small>Maps</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-yellow">
                  <i class="ni ni-basket"></i>
                </span>
                <small>Shop</small>
              </a>
            </div>
          </div>
        </li> -->
      </ul>
      {% if user.is_authenticated %}
      <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
        <li class="nav-item dropdown">
          <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            <div class="media align-items-center">
              <span class="avatar avatar-sm rounded-circle">
                <img alt="Image placeholder" src="/static/assets/LogReg.png">
              </span>
              <div class="media-body  ml-2  d-none d-lg-block">
                <span class="mb-0 text-sm  font-weight-bold">
                  {{user.first_name }}
                </span>
              </div>
            </div>
          </a>
          <div class="dropdown-menu  dropdown-menu-right ">
            <div class="dropdown-header noti-title">
              <h6 class="text-overflow m-0">Welcome!</h6>
            </div>
            <a href="/profile" class="dropdown-item">
              <i class="ni ni-single-02"></i>
              <span>My profile</span>
            </a>
            <a target="_blank" href="https://dps.cs.ut.ee/index.html" class="dropdown-item">
              <i class="ni ni-support-16"></i>
              <span>Support</span>
            </a>
            <div class="dropdown-divider"></div>
            <a href="{{ url_for('auth.logout') }}" class="dropdown-item">
              <i class="ni ni-button-power text-red"></i>
              <span>Logout</span>
            </a>
          </div>
        </li>
      </ul>
    </div>
    {% else %}
    {% endif %}
  </div>
</nav>

website/templates/profile.html
{% extends "base.html" %} {% block title %}Spatial{% endblock %} {% block content %}


<style>
    .user-details {
        margin-top: 20px;
        padding: 20px;
        border: 2px solid #ddd;
        border-radius: 5px;
        background-color: #f5f5f5;
    }

    .user-details p {
        font-size: 18px;
        margin: 10px 0;
    }

    /* Add more styles as needed */
</style>
<div class="container-fluid" autoFocus='false'>
    <h1 class="jumbotron-text display-1 text-center mb-0" style="font-size: 150px;">
        <p class="lead jumbotron-text text-center mb-0"> <b>Profile Page</b></p>
    </h1>

    <div class="user-details">
        <p><strong>User ID:</strong> {{ results.id }}</p>
        <p><strong>User Name:</strong> {{ results.name }}</p>
        <p><strong>Email:</strong> {{ results.email }}</p>
    </div>
</div>



{% endblock %}

website/templates/scripts.html
  <script src="/static/assets/vendor/jquery/dist/jquery.min.js"></script>
  <script src="/static/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="/static/assets/vendor/js-cookie/js.cookie.js"></script>
  <script src="/static/assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
  <script src="/static/assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js"></script>

website/templates/sidenav.html
<body class="nav-open g-sidenav-show g-sidenav-pinned" style="min-height: 100vh;">
  <nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner ">
      <!-- Brand  sD_logo-->
      <div class="sidenav-header  align-items-center">
        <a class="navbar-brand" href="/">
          <img src="/static/assets/sD_logo.png" class="navbar-brand-img" alt="Spatial">
        </a>
      </div>
      <div class="navbar-inner">
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
          <!-- Nav items -->
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            {% if user.user_role == 'user' %}
            <li class="nav-item">
              <a class="nav-link {% if 'index' in segment %} active {% endif %}" href="/">
                <!-- <i class="ni ni-tv-2 text-primary"></i> -->
                <i class="ni ni-single-02 text-yellow"></i>
                <span class="nav-link-text">User Role</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if 'icons' in segment %} active {% endif %}"
                href="/dashboard?user_role={{ user_role }}">
                <i class="ni ni-tv-2 text-orange"></i>
                <span class="nav-link-text">Dashboard</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if 'map' in segment %} active {% endif %}"
                href="/XAI?user_role={{ user_role }}&MS=XAI">
                <i class="ni ni-atom text-primary"></i>
                <span class="nav-link-text">xAI</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if 'profile' in segment %} active {% endif %}"
                href="/fairness?user_role={{ user_role }}&MS=Fairness">
                <i class="ni ni-diamond text-orange"></i>
                <span class="nav-link-text">Fairness</span>
              </a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.logout') }}">
                <i class="ni ni-button-power text-red"></i>
                <span class="nav-link-text">Logout</span>
              </a>
            </li>{% endif %} {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.login') }}">
                <i class="ni ni-key-25 text-info"></i>
                <span class="nav-link-text">Login</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.sign_up') }}">
                <i class="ni ni-circle-08 text-pink"></i>
                <span class="nav-link-text">Sign Up</span>
              </a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="/about?user_role={{ user_role }}">
                <i class=" ni ni-app text-green"></i>
                <span class="nav-link-text">About</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/contact?user_role={{ user_role }}">
                <i class="ni ni-badge text-pink"></i>
                <span class="nav-link-text">Contact</span>
              </a>
            </li>
          </ul>
          <!-- Divider -->
          <hr class="my-3">
          <!-- Heading -->
          <h6 class="navbar-heading p-0 text-muted">
            <span class="docs-normal">Resources</span>
          </h6>
          <!-- Navigation -->
          <ul class="navbar-nav mb-md-3">

            <li class="nav-item">
              <a class="nav-link" target="_blank" href="https://github.com/Mrasinthe/xAI-frontend">
                <!-- <i class="ni ni-archive-2 text-red"></i> -->
                <img src="../static/assets/img/icons/common/github.svg" alt="Logo"> &nbsp; &nbsp;
                <span class="nav-link-text text-red">Github</span>
              </a>
            </li>

            <!-- <li class="nav-item">
              <a class="nav-link" target="_blank" href="https://appseed.us/admin-dashboards/flask-dashboard-argon-pro">
                <i class="ni ni-spaceship text-red"></i>
                <span class="nav-link-text text-red">PRO Version</span>
              </a>
            </li> -->

            <li class="nav-item">
              <a class="nav-link active active-pro" target="_blank" href="https://dps.cs.ut.ee/index.html">
                <i class="ni ni-send text-dark"></i>
                <span class="nav-link-text">Support</span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</body>

website/templates/signup.html
{% extends "base.html" %}

{% block title %}
Sign Up
{% endblock %}

{% block content %}
<section class="vh-80" style="margin-top: 70px; overflow-x: hidden;">
  <div class="row justify-content-center">
    <div class="col-lg-12 col-xl-11">
      <div class="card text-white p-md-5"
        style="border-radius: 25px; box-shadow: 0px 0px 5px 0px rgba(0, 0, 0, 0.75); overflow: hidden;">
        <div class="card-body p-md-5">
          <div class="row justify-content-center">
            <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
              <form method="POST" style="color: black; ">
                <h3 align="center">Sign Up</h3><br>
                <div class="form-group">
                  <label for="email">Email Address</label>
                  <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" />
                </div>
                <div class="form-group">
                  <label for="firstName">Username</label>
                  <input type="text" class="form-control" id="firstName" name="firstName"
                    placeholder="Enter username" />
                </div>
                <div class="form-group">
                  <label for="password1">Password</label>
                  <input type="password" class="form-control" id="password1" name="password1"
                    placeholder="Enter password" />
                </div>
                <div class="form-group">
                  <label for="password2">Password (Confirm)</label>
                  <input type="password" class="form-control" id="password2" name="password2"
                    placeholder="Confirm password" />
                </div>
                <br />
                <div class="text-center">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

website/templates/unauthorized.html
{% extends "base.html" %} {% block title %}Spatial{% endblock %} {% block content %}


<style>
    .user-details {
        margin-top: 20px;
        padding: 20px;
        border: 2px solid #ddd;
        border-radius: 5px;
        background-color: #f5f5f5;
    }

    .user-details p {
        font-size: 18px;
        margin: 10px 0;
        color: red;
    }

    /* Add more styles as needed */
</style>
<div class="container-fluid" autoFocus='false'>


    <div class="user-details">
        <h1 class="jumbotron-text display-1 text-center mb-0" style="font-size: 150px;">
            <!-- <p class="lead jumbotron-text text-center mb-0 "> <b>Unauthorized Page..Go Back!!</b></p> -->
            <h1 class="display-4 text-center">Unauthorized Page</h1>
            <p class="lead text-center">You do not have permission to access this page. Please go back to the home page.
            </p>
        </h1>

    </div>
</div>




{% endblock %}

website/templates/userRole.html
{% extends "base.html" %}
{% block title %}UserRole{% endblock %}
{% block content %}

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <style>
    /* Add styles for the container */
    .container-fluid {
      max-width: 100%;
      /* Adjust as needed */
      padding: 0;
      left: 50%;
    }

    /* Add styles for the card */
    .card {
      border-radius: 25px;
      box-shadow: 0px 0px 5px 0px rgba(0, 0, 0, 0.75);
    }

    /* Center the form vertically and horizontally */
    .vh-80 {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 80vh;
      /* margin-top: 10px; */
    }

    /* Add responsive styles for form elements */
    @media (max-width: 768px) {
      .col-md-10 {
        max-width: 100%;
      }
    }
  </style>
</head>

<body>
  <section class="vh-80">
    <div class="container-fluid">
      <div class="row justify-content-center">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-white p-md-5 navbar-dark">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                  <form method="POST">
                    <h3 align="center">Select Your User Role</h3><br />
                    <div class="form-group">
                      <label for="user_role" style="color: black;">Role</label>
                      <select id="user_role" class="form-control" name="user_role">
                        <option value="User">User</option>
                        <option value="Developer">Developer</option>
                        <option value="Auditor">Auditor</option>
                        <option value="Business">Business</option>
                      </select>
                    </div>
                    <br />
                    <div class="text-center">
                      <button type="submit" class="btn btn-primary">Select Role</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</body>
{% endblock %}